main: main.c ../NRs/ansi/recipes/gaussj.c ../NRs/ansi/recipes/nrutil.c
	gcc -o main \
	    main.c \
	    ../NRs/ansi/recipes/gaussj.c \
	    ../NRs/ansi/recipes/nrutil.c \
	    -I../NRs/ansi/other -lm

clean:
	rm -f main
