main : main.c ../NRs/ansi/recipes/gaussj.c ../NRs/ansi/recipes/ludcmp.c ../NRs/ansi/recipes/lubksb.c ../NRs/ansi/recipes/mprove.c ../NRs/ansi/recipes/svdcmp.c ../NRs/ansi/recipes/svbksb.c ../NRs/ansi/recipes/nrutil.c
	gcc -o main main.c ../NRs/ansi/recipes/gaussj.c ../NRs/ansi/recipes/ludcmp.c ../NRs/ansi/recipes/lubksb.c ../NRs/ansi/recipes/mprove.c ../NRs/ansi/recipes/svdcmp.c ../NRs/ansi/recipes/svbksb.c ../NRs/ansi/recipes/nrutil.c -I../NRs/ansi/other -lm

clean :
	rm -f main
