main : main.c ../NRs/ansi/recipes/gasdev.c ../NRs/ansi/recipes/ran1.c ../NRs/ansi/recipes/ran2.c ../NRs/ansi/recipes/nrutil.c
	gcc -o main main.c ../NRs/ansi/recipes/gasdev.c ../NRs/ansi/recipes/ran1.c ../NRs/ansi/recipes/ran2.c ../NRs/ansi/recipes/nrutil.c -I../NRs/ansi/other -lm

clean :
	rm -f main
