main : main.c muller.c ../NRs/ansi/recipes/nrutil.c ../NRs/ansi/recipes/rtbis.c ../NRs/ansi/recipes/rtflsp.c ../NRs/ansi/recipes/rtnewt.c ../NRs/ansi/recipes/rtsafe.c ../NRs/ansi/recipes/rtsec.c ../NRs/ansi/recipes/zbrak.c ../NRs/ansi/recipes/bessj0.c ../NRs/ansi/recipes/bessj1.c
	gcc -o main main.c muller.c ../NRs/ansi/recipes/nrutil.c ../NRs/ansi/recipes/rtbis.c ../NRs/ansi/recipes/rtflsp.c ../NRs/ansi/recipes/rtnewt.c ../NRs/ansi/recipes/rtsafe.c ../NRs/ansi/recipes/rtsec.c ../NRs/ansi/recipes/zbrak.c ../NRs/ansi/recipes/bessj0.c ../NRs/ansi/recipes/bessj1.c -I../NRs/ansi/other -lm

clean :
	rm -f main
